language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
env:
  global:
    - secure: "Y94kVKSbboNJnFK6UGL2BKWLtbN692tCl0prYh4Ivq5taHET5Phi9TRKA64AaXXndxNqLk8ALoMuQDsJcpXjYGQjK7aM6VXOTLHjIhE0d2kJuC+ibhm04MhUhG4PrbOMJLg6jqS11fSLeqy/CkawzOVcia6ACV3aB44uTnu79g0="
    - secure: "FmQEUPLe9lBG5rT7qkrPwZsOyULX3pmKgru4bC3ZrST6ibCaAmT/TfLZ/XqHrvGeaP0vKu7daqlgrpbIkzBfxeJ+UZYL4T5F2yTLSgoigs4mGaDgt3zZvuzGEffJV+drgQVuHeEBKtT+f3BQ1UnLTKREjgRgwbIVmQ6GHKxwU1s="
    - CIBW_PLATFORM=linux
    - CIBW_SKIP="cp26-* cp33-*"
    - CIBW_BEFORE_BUILD="{pip} install -r requirements.txt"
sudo: required
services:
  - docker
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install --upgrade pip
  - pip install --only-binary ":all:" tox codecov
before_script: git clone https://github.com/pkgcore/pkgdist.git
script:
  - tox -e travis
  - pkgdist/build-dist-files.sh
after_success:
  # upload coverage data
  - pushd .tox/travis/lib/python*/site-packages
  - codecov
  - popd
