dist: bionic
language: python
python:
- 3.6
- 3.7
- 3.8
addons:
  apt:
    packages:
    - cpanminus
cache:
  pip: true
  directories:
  - $HOME/downloads

install:
- pip install -U tox
# install deps for perl checks
- sudo cpanm --quiet --notest Gentoo::PerlMod::Version
before_script:
- git clone https://github.com/pkgcore/pkgdist.git
- pkgdist/ci.sh
script: tox -e travis

stages:
  - name: test
    if: NOT branch IN (lint, deploy)
  - name: deploy
    if: (type = api) OR (branch = deploy) OR (tag IS present)

jobs:
  include:
    # push tarball and wheels to pypi
    - stage: deploy
      sudo: required
      services:
      - docker
      env:
      - secure: Y94kVKSbboNJnFK6UGL2BKWLtbN692tCl0prYh4Ivq5taHET5Phi9TRKA64AaXXndxNqLk8ALoMuQDsJcpXjYGQjK7aM6VXOTLHjIhE0d2kJuC+ibhm04MhUhG4PrbOMJLg6jqS11fSLeqy/CkawzOVcia6ACV3aB44uTnu79g0=
      - secure: FmQEUPLe9lBG5rT7qkrPwZsOyULX3pmKgru4bC3ZrST6ibCaAmT/TfLZ/XqHrvGeaP0vKu7daqlgrpbIkzBfxeJ+UZYL4T5F2yTLSgoigs4mGaDgt3zZvuzGEffJV+drgQVuHeEBKtT+f3BQ1UnLTKREjgRgwbIVmQ6GHKxwU1s=
      - CIBW_PLATFORM=linux
      - CIBW_BUILD="cp36-*"
      - CIBW_BEFORE_BUILD="tar -xf /host/$HOME/downloads/\$(uname -m)/*.tar.gz -C / && pip install -r requirements/wheel.txt"
      - CIBW_ENVIRONMENT="PATH=/opt/bin:\$PATH"
      - CIBW_TEST_COMMAND="pip install -r {project}/requirements/test.txt && py.test {project}/tests"
      before_script:
      - git clone https://github.com/pkgcore/pkgdist.git
      - pkgdist/ci.sh
      script: pkgdist/build-dist-files.sh
      after_success:

    # push tarball to github
    - stage: deploy
      before_script:
      - git clone https://github.com/pkgcore/pkgdist.git
      - pkgdist/ci.sh
      - pip install -r requirements/sdist.txt
      script: python setup.py sdist -v
      after_success: tar -ztf dist/*.tar.gz | sort
      deploy:
        provider: releases
        api_key:
          secure: nrzYgK7cioTKg44hqEj6G5VKQO7/3kyOLbUBsncrMWCl/YohM2aQGzuubDiF6bjwioOvhlVe1lUKqwuperslUmg8vyh0zsFFeAZ6pbc2xDzkCXmwK1l0Z696mAnm6SYfAuGEmBsfkEKU97ac3NE3aQuRLDcSQeYqpVOVmWHHbIY=
        file_glob: true
        file: dist/*.tar.gz
        skip_cleanup: true
        on:
          tags: true
