language: python
python:
    - 2.7
    - 3.2
    - 3.3
install:
    - git clone git://github.com/pkgcore/snakeoil.git
    - pushd snakeoil
    - python setup.py install --install-headers "${VIRTUAL_ENV}"/include/snakeoil
    - popd
    - git clone git://github.com/pkgcore/pkgcore.git pkgcore-lib
    - pushd pkgcore-lib
    - python setup.py build_ext -I "${VIRTUAL_ENV}"/include
    - python setup.py install --disable-man-pages --disable-html-docs
    - popd
script:
    - python setup.py test
