language: python
python:
    - 2.7
    - 3.3
    - 3.4
before_install:
    # add user/group for portage and wheel
    - sudo groupadd wheel
    - sudo groupadd -g 250 portage
    - sudo useradd -u 250 -g 250 portage
install:
    - git clone git://github.com/pkgcore/snakeoil.git
    - pushd snakeoil
    - python setup.py install --install-headers "${VIRTUAL_ENV}"/include/snakeoil
    - popd
    - git clone git://github.com/pkgcore/pkgcore.git pkgcore-lib
    - pushd pkgcore-lib
    - python setup.py build_ext -I "${VIRTUAL_ENV}"/include
    - python setup.py install --disable-man-pages --disable-html-docs
    - popd
script:
    - python setup.py test
