[build-system]
requires = [
	"wheel", "setuptools",
	"chardet",
	"lazy-object-proxy",
	"lxml",
	"pathspec",
	"tree-sitter",
	"snakeoil @ https://github.com/pkgcore/snakeoil/archive/master.tar.gz",
	"pkgcore @ https://github.com/pkgcore/pkgcore/archive/master.tar.gz",
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra"
testpaths = ["tests"]
