name: release

on:
  push:
    branches: [deploy]
    tags: [v*]

jobs:
  build-sdist:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        # install deps required for building sdist/wheels
        python -m pip install --upgrade pip
        pip install -r requirements/dist.txt -r requirements/test.txt

    - name: Test with pytest
      env:
        PY_COLORS: 1 # forcibly enable pytest colors
      run: python setup.py test

    - name: Build sdist
      run: |
        git clean -fxd
        # build sdist
        python setup.py sdist
        # run in-place build so wheel deps use release versions
        python setup.py build_py -i

    - name: Output dist file info
      run: |
        tar -ztf dist/*.tar.gz | sort

    - name: Upload sdist artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/*.tar.gz


  build-wheel:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pyver: [cp38, cp39, cp310, cp311]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build wheels
      uses: joerick/cibuildwheel@v2.10.0
      with:
        output-dir: dist
      env:
        CIBW_BUILD: ${{matrix.pyver}}-*
        CIBW_ARCHS_LINUX: x86_64
        CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_24
        CIBW_BEFORE_BUILD: pip install -r {project}/requirements/dist.txt && {project}/.github/workflows/manylinux.sh
        CIBW_BEFORE_TEST: pip install -r {project}/requirements/test.txt
        CIBW_ENVIRONMENT: PY_COLORS=1
        CIBW_TEST_COMMAND: pytest -v {project}/tests

    - name: Upload wheel artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/*.whl


  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    needs: ["build-sdist", "build-wheel"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist

    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        print_hash: true

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*.tar.gz
        fail_on_unmatched_files: true
